---
- name: Package installation
  hosts: localhost
  vars:
    pack: httpd

  tasks:
  - name: Install package
    yum:
      name: "{{ pack }}"
      state: present

  - name: Start package
    service:
      name: "{{ pack }}"
      state: started
      enabled: yes
