---
- name: Setup Apache and Open Firewall Port
  hosts: all

  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: present

  - name: Open http service port in firewall
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled
    notify:
    - Restart firewalld service

  - name: Open https service port in firewall
    firewalld:
      service: https
      permanent: yes
      immediate: yes
      state: enabled
    notify:
    - Restart firewalld service

  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  handlers:
  - name: Restart firewalld service
    service:
      name: firewalld
      state: restarted



